# Generated by Django 3.1.7 on 2021-03-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField()),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('time', models.TextField()),
            ],
            options={
                'db_table': 'Reviews',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
