# Generated by Django 3.1.6 on 2021-05-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0002_auto_20210313_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
            options={
                'db_table': 'Summary',
            },
        ),
        migrations.AlterModelTable(
            name='review',
            table='Review',
        ),
    ]
